# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install bs4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        ./Shadowrocket-ADBlock-Rules/factory/auto_build.sh
    - name: Publish GitHub Action
      # You may pin to the exact commit or the version.
      # uses: tgymnich/publish-github-action@2d97003656685a260a74c3d8516dc9f1077e0802
      uses: tgymnich/publish-github-action@v1.1.9
      with:
        # Token for the github API
        github_token: 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
